spring:
  profiles:
    active: db
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    hikari:
      transaction-isolation: "read-committed" # this is necessary so that we won't get uncommitted data on listWidgets and getWidget
  
logging:
  level:
    pashazz.widgetmanager: DEBUG
